### ISSUE TITLE
[TASK] Update fixtures 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/protocol-substrate#179]
**Task summary**

**On protocol-substrate**
- [ ] Update the fixtures to the branch in progress that is being updated
- [ ] Update the paths and ensure tests pass
- [ ] Open a PR to point to the branch in fixtures to demonstrate tests pass there
- [ ] Change the fixtures url of protocol-substrate back to main

**On protocol-cosmwasm**
- [ ] Change the fixtures url on protocol-cosmwasm back to main
